site_name: My Docs
site_description: postgres-declare, declarative layer for everything Postgres.
site_url: https://TODO
theme:
  name: material
  palette:
  - scheme: default
    primary: purple
    accent: white
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - scheme: slate
    primary: purple
    accent: gray
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en
repo_name: raaidarshad/postgres-declare
repo_url: https://github.com/raaidarshad/postgres-declare
edit_uri: ''
nav:
  - postgres-declare: index.md
  - quickstart.md
  - User guide:
    - guide/index.md
    - guide/controller.md
    - guide/databases.md
    - guide/roles.md
    - guide/schemas.md
    - guide/tables-and-columns.md
    - guide/grants.md
  - help.md
  - contributing.md

markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- admonition
- codehilite
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tabbed:
    alternate_style: true
#- mdx_include

extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/raaidarshad/postgres-declare
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/RaaidNajeeb
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/raaid-arshad
  - icon: fontawesome/solid/globe
    link: https://www.raaid.xyz
